# Generated by Django 5.0.4 on 2025-04-18 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='custom_date',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
