# Generated by Django 5.0.4 on 2025-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_remove_cashflow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
